todo/urls.py
from django.urls import path

from todo.views import (
    HomePageView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagsListView,
    TagsCreateView,
    TagsUpdateView,
    TagsDeleteView,
    toggle_complate_task
)

urlpatterns = [
    path(
        "",
        HomePageView.as_view(),
        name="index"
    ),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/<int:pk>/complate/",
        toggle_complate_task,
        name="task-complete"
    ),
    path(
        "tags/",
        TagsListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagsCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagsUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagsDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    marker = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ("marker", "-created")

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            }
        ),
        required=False,
    )

    class Meta:
        model = Task
        fields = "__all__"

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


class HomePageView(generic.ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/index.html"
    paginate_by = 5


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagsListView(generic.ListView):
    model = Tag
    template_name = "todo/tag-list.html"
    context_object_name = "tags"
    paginate_by = 5


class TagsCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagsUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagsDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


def toggle_complate_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.marker = not task.marker
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary">
      Add task
    </a>
  </h1>

  {% if tasks %}
    <ul class="list-group list-group-flush">
      {% for task in tasks %}
        <li class="list-group-item">
          <p class="font-weight-bold">{{ task.content }} {% if task.marker %}
            <span style="color: green;">
            Done
          </span>
          {% else %}
            <span style="color: red;">
            Not done
          </span>
          {% endif %}
            {% if task.marker %}
              <a class="btn btn-secondary" href="{% url 'todo:task-complete' pk=task.id %}">
                Undo
              </a>
            {% else %}
              <a class="btn btn-success" href="{% url 'todo:task-complete' pk=task.id %}">
                Complete
              </a>
            {% endif %}
          <p>Created: {{ task.created }}
            {% if task.deadline %}
              <span style="color: darkred">
          Deadline: {{ task.deadline }}
        </span>
            {% endif %}</p>
          <p>Tags:
            {% if task.tags.all %}
              {% for tag in task.tags.all %}
                {{ tag.name }}
              {% endfor %}
            {% else %}
              No tags
            {% endif %}
            <a href="{% url 'todo:task-update' pk=task.id %}">
              Update
            </a>
            <a href="{% url 'todo:task-delete' pk=task.id %}">
              Delete
            </a></p>
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/todo/tag-list.html
{% extends 'base.html' %}
{% block content %}
  <h1>
    Tags
    <a class="btn btn-primary" href="{% url 'todo:tag-create' %}">Add</a>
  </h1>

  {% if tags %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tags %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo:tag-update' tag.id %}" class="btn btn-secondary">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'todo:tag-delete' tag.id %}" class="btn btn-danger">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class=" container">
    <div class="confirmation-box">
      <h1 class="text-primary">Delete tag?</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-actions">
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class=" container">
    <div class="confirmation-box">
      <h1 class="text-primary">Delete task</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-actions">
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'todo:index' %}" class="btn btn-secondary">Cancel</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}